=== alankent/shared-services/xsd/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="https://magento.com/open-specification"
           xmlns="https://magento.com/open-specification"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="specification" type="SpecificationType"/>

  <xs:group name="DescriptionGroup">
    <xs:sequence>
      <xs:element type="xs:string" name="summary" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:group>

  <xs:complexType name="SpecificationType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ImportType" name="import"/>
        <xs:element type="ModuleType" name="module"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ModuleType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element type="ServiceType" name="service"/>
        <xs:element type="StructType" name="struct"/>
        <xs:element type="EnumType" name="enum"/>
        <xs:element type="ExtensionType" name="extension"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ModuleNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ImportType">
    <xs:attribute type="xs:token" name="location" use="required"/>
  </xs:complexType>

  <xs:complexType name="ServiceType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element type="QueryType" name="query"/>
        <xs:element type="EventType" name="event"/>
        <xs:element type="CommandType" name="command"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="ServiceNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="InteractionType" abstract="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="arguments" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="argument" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="InteractionNameType" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="CommandType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="QueryType">
    <xs:complexContent>
      <xs:extension base="InteractionType">
        <xs:sequence>
          <xs:element type="xs:token" name="returns" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="EventType">
    <xs:complexContent>
      <xs:extension base="InteractionType"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="StructType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="xs:boolean" name="extensible" minOccurs="1"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ExtensionType" mixed="true">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element name="properties" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="PropertyType" name="property" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:token" name="extends" use="required"/>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:sequence>
      <xs:group ref="DescriptionGroup"/>
      <xs:element type="PropertyTypeNameType" name="type" minOccurs="1"/>
      <xs:element type="xs:boolean" name="required" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="EnumType">
    <xs:sequence>
      <xs:element type="xs:token" name="value" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:token" name="name" use="required"/>
  </xs:complexType>

  <xs:simpleType name="PropertyTypeNameType">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

  <xs:simpleType name="ModuleNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ServiceNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InteractionNameType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z][a-z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== alankent/shared-services/inventory/source.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

  <module name="magento.inventory">
    <service name="source_stock_management">
      <summary>Source Stock Management</summary>

      <command name="update">
        <summary>Update stock information for an SKU</summary>
        <extensible>true</extensible>
        <arguments>
          <argument name="stock">
            <summary>Stock</summary>
            <type>magento.inventory.source_stock</type>
            <required>true</required>
          </argument>
        </arguments>
      </command>

      <event name="updated">
        <summary>Notification about stock update</summary>
        <extensible>true</extensible>
        <arguments>
          <argument name="stock">
            <summary>Stock</summary>
            <type>magento.inventory.source_stock</type>
            <required>true</required>
          </argument>
        </arguments>
      </event>
    </service>

    <service name="source_stock_repository">
      <summary>Source Stock Repository</summary>

      <query name="online_stock_availability">
        <summary>Check online store stock availability for multiple SKU</summary>
        <extensible>false</extensible>
        <arguments>

        </arguments>
        <returns>array[magento.inventory.source_stock]</returns>
      </query>

      <query name="nearby_stock_availability">
        <summary>Check nearby store stock availability for multiple SKU</summary>
        <extensible>false</extensible>
        <arguments>

        </arguments>
        <returns>array[magento.inventory.source_stock]</returns>
      </query>

      <query name="find">
        <summary>Find stock information for given SKU</summary>
        <extensible>false</extensible>
        <arguments>
          <argument name="query">
            <summary>Search Query</summary>
            <type>magento.common.query</type>
            <required>true</required>
          </argument>
        </arguments>
        <returns>array[magento.inventory.source_stock]</returns>
      </query>
    </service>

    <struct name="source">
      <summary>Source</summary>
      <extensible>true</extensible>
      <properties>
        <property name="id">
          <summary>Unique identifier</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="name">
          <summary>Human friendly name</summary>
          <type>string</type>
          <required>true</required>
        </property>
      </properties>
    </struct>

    <struct name="source_stock">
      <summary>Source Stock</summary>
      <description>
        Stock represent a real stock level in a certain source
      </description>
      <extensible>true</extensible>
      <properties>
        <property name="sku">
          <summary>The sku of the product</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="quantity">
          <summary>The units of the product available</summary>
          <type>float</type>
          <required>true</required>
        </property>
        <property name="source_id">
          <summary>The identifier of the source who owns the stock unit</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="type">
          <summary>The type of stock (GOOD, DAMAGED, REPAIRED ...)</summary>
          <type>string</type>
          <required>false</required>
        </property>
      </properties>
    </struct>

  </module>

</specification>

=== alankent/shared-services/catalog/category.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

  <module name="magento.catalog">

    <service name="category_management">
      <summary>Category Management</summary>

      <command name="update">
        <summary>Update category properties</summary>
        <extensible>false</extensible>
        <arguments>
          <argument name="category">
            <summary>Category</summary>
            <type>magento.catalog.category</type>
            <required>true</required>
          </argument>
        </arguments>
      </command>

      <command name="delete">
        <summary>Delete an existing category properties</summary>
        <extensible>false</extensible>
        <arguments>
          <argument name="category_id">
            <summary>Category Unique Identifier</summary>
            <type>string</type>
            <required>true</required>
          </argument>
        </arguments>
      </command>

      <event name="updated">
        <summary>Triggered once category updated</summary>
        <extensible>false</extensible>
        <arguments>
          <argument name="category">
            <summary>Category</summary>
            <type>magento.catalog.category</type>
            <required>true</required>
          </argument>
        </arguments>
      </event>

      <event name="deleted">
        <summary>Triggered once category deleted</summary>
        <extensible>false</extensible>
        <arguments>
          <argument name="category">
            <summary>Category</summary>
            <type>magento.catalog.category</type>
            <required>true</required>
          </argument>
        </arguments>
      </event>
    </service>

    <service name="category_repository">
      <summary>Category Repository</summary>

      <query name="find">
        <summary>Find categories by criteria</summary>
        <extensible>true</extensible>
        <arguments>
          <argument name="query">
            <summary>Search Query</summary>
            <type>magento.common.query</type>
            <required>true</required>
          </argument>
        </arguments>
        <returns>array[magento.catalog.category]</returns>
      </query>

      <query name="get">
        <summary>Fetch category by Unique identifier</summary>
        <extensible>true</extensible>
        <arguments>
          <argument name="id">
            <summary>Unique Identifier</summary>
            <type>string</type>
            <required>true</required>
          </argument>
        </arguments>
        <returns>magento.catalog.category</returns>
      </query>
    </service>

    <struct name="category">
      <summary>Category Data Model</summary>
      <extensible>true</extensible>
      <properties>
        <property name="id">
          <summary>Unique Identifier</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="name">
          <summary>Name</summary>
          <type>string</type>
          <required>true</required>
        </property>
      </properties>
    </struct>

  </module>
</specification>

=== alankent/shared-services/inventory/aggregation.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

  <module name="magento.inventory">
    <service name="aggregation_management">
      <summary>Stock Aggregation Management</summary>

      <event name="updated">
        <summary>Notification about stock aggregation update</summary>
        <extensible>false</extensible>
        <arguments>
          <argument name="aggregation">
            <summary>Aggregation</summary>
            <type>magento.inventory.aggregation</type>
            <required>true</required>
          </argument>
        </arguments>
      </event>
    </service>

    <service name="aggregation_stock_management">
      <summary>Stock Aggregation Management</summary>

      <event name="updated">
        <summary>Notification about stock aggregation update</summary>
        <extensible>false</extensible>
        <arguments>
          <argument name="stock">
            <summary>Aggregation Stock</summary>
            <type>magento.inventory.aggregation_stock</type>
            <required>true</required>
          </argument>
        </arguments>
      </event>
    </service>

    <struct name="aggregation">
      <summary>Stock Aggregation</summary>
      <description>
        Stock Aggregation represent a group of stock items aggregated by some criteria
      </description>
      <extensible>true</extensible>
      <properties>
        <property name="id">
          <summary>Unique identifier</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="name">
          <summary>Human friendly name</summary>
          <type>string</type>
          <required>true</required>
        </property>
      </properties>
    </struct>

    <struct name="aggregation_stock">
      <summary>Aggregated stock</summary>
      <description>
        Aggregated stock represents available stock in a certain channel
      </description>
      <extensible>true</extensible>
      <properties>
        <property name="aggregation_id">
          <summary>The identifier of the aggregation which this stock belongs to</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="sku">
          <summary>The sku of the product</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="quantity">
          <summary>The units of the product available</summary>
          <type>float</type>
          <required>true</required>
        </property>
        <property name="in_stock">
          <summary>If the product is in stock or not</summary>
          <description>A flag to mark if the product if it's in stock or not independently of the number of units available</description>
          <type>boolean</type>
          <required>false</required>
        </property>
        <property name="safety_stock">
          <summary>Number of units that we don't take into consideration</summary>
          <description>The number of units available that we don't want to take into consideration when computing stock</description>
          <type>float</type>
          <required>false</required>
        </property>
        <property name="is_backorderable">
          <summary>If the product is available for backorders</summary>
          <type>boolean</type>
          <required>false</required>
        </property>
        <property name="is_preorderable">
          <summary>If the product is available for preorders</summary>
          <type>boolean</type>
          <required>false</required>
        </property>
        <property name="type">
          <summary>The type of stock (GOOD, DAMAGED, REPAIRED ...)</summary>
          <type>string</type>
          <required>false</required>
        </property>
      </properties>
    </struct>

  </module>

</specification>

=== alankent/shared-services/docs/service-specifications/magento.common.xml
<?xml version="1.0" encoding="UTF-8"?>

<specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://magento.com/open-specification"
               xsi:schemaLocation="https://magento.com/open-specification ../specification.xsd">

  <module name="magento.common">

    <typedef name="by_locale[T]">
      <type>array[magento.common.by_locale_entry[T]]</type>
    </typedef>

    <struct name="by_locale_entry[T]">
      <summary>Holds value keyed by locale</summary>
      <extensible>false</extensible>
      <properties>
        <property name="locale">
          <summary>The locale value (such as 'en_US'), or '*' to match all locales</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="value">
          <summary>The value for that locale</summary>
          <type>T</type>
          <required>true</required>
        </property>
      </properties>
    </struct>

    <typedef name="by_channel[T]">
      <summary>Store values by channel</summary>
      <description>
        Used to hold a set of values applicable per channel.
	To find a match, the rule is to start from the top of the table
	and work the way down until the first match is found.
	A value of "*" in this array will match all channel names.
      </description>
      <type>array[magento.common.by_channel_entry[T]]</type>
    </typedef>

    <struct name="by_channel_entry[T]">
      <summary>Holds value keyed by channel</summary>
      <extensible>false</extensible>
      <properties>
        <property name="channel">
          <summary>The channel value (such as 'mobile'), or '*' to match all channels</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="value">
          <summary>The value for the specified channel</summary>
          <type>T</type>
          <required>true</required>
        </property>
      </properties>
    </struct>

    <typedef name="by_locale_and_channel[T]">
      <summary>Store values per locale and channel combination</summary>
      <description>
        Used to hold a set of values applicable per combination of locale
	and channel (e.g. for mobile in Spain use "es_ES"/"mobile").
	To find a match, the rule is to start from the top of the table
	and work the way down until the first match is found.
	A value of "*" in this array will match all locale and channel names.
	This avoids having to duplicate as much information.
      </description>
      <type>array[magento.common.by_locale_and_channel_entry[T]]</type>
    </typedef>

    <struct name="by_locale_and_channel_entry[T]">
      <summary>Holds value keyed by channel</summary>
      <extensible>false</extensible>
      <properties>
        <property name="locale">
          <summary>The locale value (such as 'en_US'), or '*' to match all locales</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="channel">
          <summary>The channel value (such as 'mobile'), or '*' to match all channels</summary>
          <type>string</type>
          <required>true</required>
        </property>
        <property name="value">
          <summary>The value for the specified channel</summary>
          <type>T</type>
          <required>true</required>
        </property>
      </properties>
    </struct>

  </module>
</specification>
